loggers:
  - stream_handlers:
      - type: file
        file_path: temp/log_test_1.txt
        log_level: INVALID_VALUE
        style: yaml
        date_format: '%Y-%m'
        log_line_template: 'Test $date$ $message$'